# Generated by Django 4.1.3 on 2022-12-27 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_alter_product_created_by_alter_product_entry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('payment_uid', models.CharField(max_length=100)),
                ('total_amt', models.IntegerField()),
                ('transaction_id', models.CharField(max_length=50)),
                ('payment_method', models.CharField(choices=[('cash', 'cash'), ('digital', 'digital')], max_length=10)),
                ('cancel_status', models.BooleanField(default=False)),
                ('payment_status', models.BooleanField(default=False)),
                ('delivery_status', models.BooleanField(default=False)),
                ('order_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
            ],
        ),
    ]
