# Generated by Django 4.1.3 on 2023-01-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='username',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
