# Generated by Django 4.1.3 on 2023-01-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_uid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
